'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class competition

    '''<summary>
    '''form_competition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form_competition As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Label_na_tahu_je_hrac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_na_tahu_je_hrac As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_tomas_body_z_minulej_hry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_tomas_body_z_minulej_hry As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label_meno_hraca_na_tahu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_meno_hraca_na_tahu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_zadaj_body_za_slovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_zadaj_body_za_slovo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_zadat_body_za_slovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_zadat_body_za_slovo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_1sprava control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_1sprava As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_pomocny_text1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_pomocny_text1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_pomocny_text2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_pomocny_text2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_2sprava control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_2sprava As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_tuto_hru_zacal_napis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_tuto_hru_zacal_napis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_tuto_hru_zacal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_tuto_hru_zacal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label_tuto_hru_zacal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_tuto_hru_zacal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_cislo_tahu_popis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_cislo_tahu_popis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_cislo_tahu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_cislo_tahu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label_cislo_tahu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_cislo_tahu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Table_hraci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_hraci As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Table_rekordy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_rekordy As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableCell_drzitel_rekordu_najviac_bodov_za_slovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell_drzitel_rekordu_najviac_bodov_za_slovo As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell_bodova_hodnota_rekordu_najviac_bodov_za_slovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell_bodova_hodnota_rekordu_najviac_bodov_za_slovo As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell_datum_vytvorenia_rekordu_najviac_bodov_za_slovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell_datum_vytvorenia_rekordu_najviac_bodov_za_slovo As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell_drzitel_rekordu_najviac_bodov_za_hru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell_drzitel_rekordu_najviac_bodov_za_hru As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell_bodova_hodnota_rekordu_najviac_bodov_za_hru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell_bodova_hodnota_rekordu_najviac_bodov_za_hru As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell_datum_vytvorenia_rekordu_najviac_bodov_za_hru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell_datum_vytvorenia_rekordu_najviac_bodov_za_hru As Global.System.Web.UI.WebControls.TableCell
End Class
