'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class login

    '''<summary>
    '''formLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formLogin As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Label_login_message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_login_message As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox_login_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_login_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox_Login_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_Login_Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_login As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label_vytvorit_ucet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_vytvorit_ucet As Global.System.Web.UI.WebControls.Button
End Class
