'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class vyberHracov

    '''<summary>
    '''formVyberHracov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formVyberHracov As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Label_chybove_hlasenie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_chybove_hlasenie As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownList_players control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList_players As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label_selectedPlayer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_selectedPlayer As Global.System.Web.UI.WebControls.Label
End Class
